//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGCIJOROSystem.DAL.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.0.0.9;Initial Catalog=FGCIProductMasterlistDB;User ID=sa;Password=" +
            "1t_r3publ1cadm1n")]
        public string ProductMasterlistConnection {
            get {
                return ((string)(this["ProductMasterlistConnection"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.0.0.9;Initial Catalog=FGCILInventoryDB;User ID=sa;Password=1t_r3pu" +
            "bl1cadm1n")]
        public string InventoryConnection {
            get {
                return ((string)(this["InventoryConnection"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.0.0.9;Initial Catalog=FGCIHRDMasterlistSystemDB;User ID=sa;Passwor" +
            "d=1t_r3publ1cadm1n")]
        public string MasterlistConnection {
            get {
                return ((string)(this["MasterlistConnection"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.0.0.9;Initial Catalog=FGCIAccountingPPEMonitoringDB;User ID=sa;Pas" +
            "sword=1t_r3publ1cadm1n")]
        public string PPEConnection {
            get {
                return ((string)(this["PPEConnection"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.0.0.9;Initial Catalog=FGCIProjectEFileCabinetDB;User ID=sa;Passwor" +
            "d=1t_r3publ1cadm1n")]
        public string ProjectEFileConnection {
            get {
                return ((string)(this["ProjectEFileConnection"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.0.0.9;Initial Catalog=FGCIJOROSystemDB;Persist Security Info=True;" +
            "User ID=sa;Password=1t_r3publ1cadm1n")]
        public string JOROSystemDB {
            get {
                return ((string)(this["JOROSystemDB"]));
            }
        }
    }
}
